version: '3.2'

services:
  web_gitea:
    image: gitea/gitea:1.3.2
    volumes:
      - "/home/git/data:/data"      
    ports:
      - "8080:3000"
      - "2221:22"     
    depends_on:
      - db_gitea
    restart: always

  db_gitea:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=my_super_secret_password
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=my_super_secret_password
    volumes:
      - ./db/:/var/lib/mysql
